apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: national-parks-app
    app.kubernetes.io/part-of: national-parks-app
    component: parksmap
    role: frontend
  name: parksmap
  namespace: nationalparksapp
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: parksmap
    weight: 100
  wildcardPolicy: None