apiVersion: v1
data:
  DATABASE_SERVICE_NAME: bW9uZ29kYi1uYXRpb25hbHBhcmtz
  MONGODB_ADMIN_PASSWORD: bW9uZ29kYg==
  MONGODB_DATABASE: bW9uZ29kYg==
  MONGODB_PASSWORD: bW9uZ29kYg==
  MONGODB_USER: bW9uZ29kYg==
kind: Secret
type: Opaque
metadata:
  name: nationalparks-mongodb-parameters
  namespace: nationalparksapp