apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-nationalparks
    app.kubernetes.io/component: mongodb-nationalparks
    app.kubernetes.io/instance: mongodb-nationalparks
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: national-parks-app
  name: mongodb-nationalparks
  namespace: nationalparksapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: national-parks-app
    deployment: mongodb-nationalparks
  sessionAffinity: None
  type: ClusterIP
